function DemandBody({ title }) {

  return (
    <section id='the-unearned-increment' className='demand'>
      <div className='container'>
        <div className='row'>
          <div className='three columns sticky'>
            <h5>To decomodify housing in c/a/n/a/d/a we demand</h5>
            <h2>{title}</h2>


            <p>
              Toronto needs a mechanism to channel the profit generated by land value increase into the communities who created it, and from whom this value is being taken. <em>(This would be a slightly longer decription of the demand...)</em>
            </p>
            <label>region:</label> Toronto
            <br />
            <label>Activist:</label> Gentrification Tax Action
            <br />
            <label>Advocate:</label>
            Parkdale Neighborhood Land Trust
            <br />
            <label>Architect:</label>
            Levitt Goodman Associates

          </div>
          <div className='six columns'>
            <img src='https://server-aaha.codepanel.in/web/sites/default/files/2022-12/Affordable%20Parkdale%201.jpeg?itok=hcX127WD' />
            <p className='caption'>This is a caption</p>

            <p>
              We demand to tax the unearned increment to finance land trusts that acquire private rental housing and transform it into deeply affordable homes. The unearned increment is the value embedded in real estate, that is not created by a private owner, but rather has been built by Indigenous people, local cultures, tenants, neighbourhoods, publicly funded infrastructure and non-human biotic and abiotic ecologies. This value must be reinvested in affordable housing land trusts, in order to keep this value in the community that created it.
            </p>
            <p>
              The City of Toronto should create a hypothecated tax on the unearned increment of real estate, earmarked to create a reliable and dedicated revenue stream to maintain deeply affordable housing for locally governed community land trusts. This tax could allow multi-unit rental buildings to be purchased and secured as affordable housing. The aggregation of formerly private rental properties into a network of Land Trust properties should create new public spaces in Toronto neighbourhoods.
            </p>


            <p>
              We demand to tax the unearned increment to finance land trusts that acquire private rental housing and transform it into deeply affordable homes. The unearned increment is the value embedded in real estate, that is not created by a private owner, but rather has been built by Indigenous people, local cultures, tenants, neighbourhoods, publicly funded infrastructure and non-human biotic and abiotic ecologies. This value must be reinvested in affordable housing land trusts, in order to keep this value in the community that created it.
            </p>
            <p>
              The City of Toronto should create a hypothecated tax on the unearned increment of real estate, earmarked to create a reliable and dedicated revenue stream to maintain deeply affordable housing for locally governed community land trusts. This tax could allow multi-unit rental buildings to be purchased and secured as affordable housing. The aggregation of formerly private rental properties into a network of Land Trust properties should create new public spaces in Toronto neighbourhoods.
            </p>


            <p>
              We demand to tax the unearned increment to finance land trusts that acquire private rental housing and transform it into deeply affordable homes. The unearned increment is the value embedded in real estate, that is not created by a private owner, but rather has been built by Indigenous people, local cultures, tenants, neighbourhoods, publicly funded infrastructure and non-human biotic and abiotic ecologies. This value must be reinvested in affordable housing land trusts, in order to keep this value in the community that created it.
            </p>
            <p>
              The City of Toronto should create a hypothecated tax on the unearned increment of real estate, earmarked to create a reliable and dedicated revenue stream to maintain deeply affordable housing for locally governed community land trusts. This tax could allow multi-unit rental buildings to be purchased and secured as affordable housing. The aggregation of formerly private rental properties into a network of Land Trust properties should create new public spaces in Toronto neighbourhoods.
            </p>


            <p>
              We demand to tax the unearned increment to finance land trusts that acquire private rental housing and transform it into deeply affordable homes. The unearned increment is the value embedded in real estate, that is not created by a private owner, but rather has been built by Indigenous people, local cultures, tenants, neighbourhoods, publicly funded infrastructure and non-human biotic and abiotic ecologies. This value must be reinvested in affordable housing land trusts, in order to keep this value in the community that created it.
            </p>
            <p>
              The City of Toronto should create a hypothecated tax on the unearned increment of real estate, earmarked to create a reliable and dedicated revenue stream to maintain deeply affordable housing for locally governed community land trusts. This tax could allow multi-unit rental buildings to be purchased and secured as affordable housing. The aggregation of formerly private rental properties into a network of Land Trust properties should create new public spaces in Toronto neighbourhoods.
            </p>


            <div className='main-carousel'>
              <div className='carousel-cell'>
                <img src='https://server-aaha.codepanel.in/web/sites/default/files/2022-12/AAHA_unit_3cc.jpg?itok=BppEniI5' />
                <p className='caption'>example caption</p>
              </div>
              <div className='carousel-cell'>
                <img src='https://server-aaha.codepanel.in/web/sites/default/files/2022-12/AAHA_unit_2cc.jpg?itok=pPtOD-xP' />
                <p className='caption'>example caption</p>
              </div>
              <div className='carousel-cell'>
                <img src='https://server-aaha.codepanel.in/web/sites/default/files/2022-12/AAHA_unit_1cc.jpg?itok=8t0Is5R_' />
                <p className='caption'>example caption</p>
              </div>
            </div>
          </div>
          <div className='action-bar three columns sticky-bottom white-bg'>
            <h3>TAKE ACTION</h3>

            <ul className='actions'>
              <li>
                <label className='label--red'>donate</label><br />
                Learn more about the campaign to for a gentrification tax
                in Toronto by visiting <label>this page.</label>
                <br />
                <label>PAY THE VOLUNTARY TAX</label>
              </li>
              <li>
                <label className='label--red'>donate</label><br />
                Learn more about the campaign to for a gentrification tax
                in Toronto by visiting <label>this page.</label>
                <br />
                <label>PAY THE VOLUNTARY TAX</label>
              </li>
              <li>
                <label className='label--red'>donate</label><br />
                Learn more about the campaign to for a gentrification tax
                in Toronto by visiting <label>this page.</label>
                <br />
                <label>PAY THE VOLUNTARY TAX</label>
              </li>
              <li>
                <label className='label--red'>donate</label><br />
                Learn more about the campaign to for a gentrification tax
                in Toronto by visiting <label>this page.</label>
                <br />
                <label>PAY THE VOLUNTARY TAX</label>
              </li>

              <li>
                <label className='label--red'>Sign</label><br />
                Advocate for taxing the unearned incremenet at city hall by signing the petition below:
                <br />
                <label>Sign here</label>
              </li>

              <li>
                <label className='label--red'>participate</label><br />
                Attend one of the forthcoming Parkdale Community Information Sessions hosted by PNLT
                <label>RSVP FOR AN INFORMATION SESSION</label>
              </li>
            </ul>



          </div>
        </div>
      </div>
    </section >
  )
}

export default DemandBody